### ISSUE TITLE
many shot ICL / prompting?

### ISSUE THREAD

**Issue by agarwl** [trigaten/The_Prompt_Report#170]
Several recent papers on this topic from Anthropic (Claude-2), GDM (our work with Gemini 1.5 Pro with 1M context), CMU (open models) and Stanford (multimodal ICL)

https://arxiv.org/abs/2404.11018
https://www.anthropic.com/research/many-shot-jailbreaking
https://arxiv.org/abs/2405.00200
https://arxiv.org/abs/2405.09798

**Comment by trigaten** [comment]
@Mcilie please decide if appropriate then add the relevant citations. I will consider jb stuff out of scope.

**Comment by Mcilie** [comment]
added
