### ISSUE TITLE
Update Fig 2.3

### ISSUE THREAD

**Issue by nbalepur** [trigaten/The_Prompt_Report#191]
I added "Instruction Selection" as a few-shot prompting practice (i.e. adding an instruction before the exemplars), so we might want to update Figure 2.3 appropriately

The [NAACL paper](https://aclanthology.org/2024.findings-naacl.270/) actually disccuses that instructions are not always super helpful for accuracy (LLMs can learn to follow instructions mainly from exemplars), but there's some evidence that they are good for response style. I think either adding or omitting this to the figure would work, it's your call

**Comment by trigaten** [comment]
Omitting from fig for simplicity
